import "./globals.css";
import Navbar from "./components/Navbar";
import { Urbanist } from "next/font/google";
import Providers from "@/app/providers"; // নতুন wrapper
import Link from "next/link";


import Footer from "@/app/components/Footer";


const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={urbanist.className}>
        <Navbar />
      
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
